apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-spring-boot
  description: Java Spring Boot scaffolding to begin developing a new Java application using the Maven project management and software build tool.
  annotations:
    github.com/project-slug: knowmad-mood/demo-spring-boot
spec:
  owner: knowmad-mood
  type: service
  lifecycle: development
  system: default
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - java_package_name
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        java_package_name:
          title: Java Package Name
          type: string
          description: Name for the java package. eg (io.backstage.blah)
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
